services:

  postgres:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      appstore-network:
        ipv4_address: 172.19.0.2
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: appstore
      POSTGRES_DB: appstore

  registry:
    image: registry:latest
    volumes:
      - registry_data:/data
    ports:
      - 5000:5000
    networks:
      appstore-network:
        ipv4_address: 172.19.0.3
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: true
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data

  backend:
    build:
      context: backend
    volumes:
      - backend_data:/data
    ports:
      - "8082:8082"
    networks:
      appstore-network:
        ipv4_address: 172.19.0.4
    environment:
      DB_HOST: postgres
      REGISTRY_HOST: registry
    depends_on:
      - postgres
      - registry
    restart: unless-stopped

  frontend:
    build:
      context: frontend
      target: dev-server
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      appstore-network:
        ipv4_address: 172.19.0.5
    env_file:
      - .env.frontend
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_data:
  postgres_data:
  registry_data:

networks:
  appstore-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
