apiVersion: apps/v1
kind: Deployment
metadata:
  name: appstore-frontend
  labels:
    app: appstore-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appstore-frontend
  template:
    metadata:
      labels:
        app: appstore-frontend
      annotations:
        checksum/config: "{{ include (print $.Template.BasePath "/frontend/frontend-config.yaml") . | sha256sum }}"
    spec:
      securityContext:
      {{- include "cytomine.podSecurityContext" . | nindent 8 }}
      volumes:
      - name: web-ui-config
        configMap:
          name: web-ui-config
      - name: nginx
        emptyDir: {}
      - name: nginx-pid
        emptyDir: {}
      containers:
      - name: appstore-frontend
        image: {{ .Values.appstore_frontend.image }}
        securityContext:
        {{- include "cytomine.containerSecurityContext" . | nindent 10 }}
        ports:
        - containerPort: {{ .Values.appstore_frontend.port }}
        envFrom:
        - configMapRef:
            name: appstore-frontend
        volumeMounts:
        - name: nginx
          mountPath: /var/cache/nginx
        - name: nginx-pid
          mountPath: /var/run
        - name: web-ui-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
