apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: appstore
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: {{ .Values.global.domainName }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: public
  rules:
    - host: {{ .Values.global.domainName }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: appstore-backend
                port:
                  number: {{ .Values.appstore_backend.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: appstore-frontend
                port:
                  number: {{ .Values.appstore_frontend.port }}
  tls:
  - hosts:
    - {{ .Values.global.domainName }}
    secretName: ingress-tls-appstore
