apiVersion: apps/v1
kind: Deployment
metadata:
  name: appstore-backend
  labels:
    app: appstore-backend
spec:

  replicas: 1
  selector:
    matchLabels:
      app: appstore-backend
  template:
    metadata:
      labels:
        app: appstore-backend
      annotations:
        checksum/config: "{{ include (print $.Template.BasePath "/backend/backend-config.yaml") . | sha256sum }}"
    spec:
      securityContext:
      {{- include "cytomine.podSecurityContext" . | nindent 8 }}
      volumes:
      - name: temp
        emptyDir: {}
      containers:
      - name: appstore-backend
        image: {{ .Values.appstore_backend.image }}
        securityContext:
        {{- include "cytomine.containerSecurityContext" . | nindent 10 }}
        ports:
        - containerPort: {{ .Values.appstore_backend.port }}
        envFrom:
        - configMapRef:
            name: appstore-backend
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-appstore-backend-secret
              key: password
        volumeMounts:
          - name: temp
            mountPath: /tmp
