name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-frontend:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Set up the repository
        uses: actions/checkout@v5

      - name: Set up NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install Dependencies
        run: npm ci

      - name: Check lint
        run: npm run lint

  type-check-frontend:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Set up the repository
        uses: actions/checkout@v5

      - name: Set up NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install Dependencies
        run: npm ci

      - name: Check type
        run: npm run type-check

  test-frontend:
    runs-on: self-hosted
    needs:
    - lint-frontend
    - type-check-frontend
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Set up the repository
        uses: actions/checkout@v5

      - name: Set up NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install Dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:unit

  e2e-tests-frontend:
    needs:
      - test-backend
      - test-frontend

    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.55.0-noble
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Set up the repository
        uses: actions/checkout@v5

      - name: Install dependencies and build
        run: npm ci && npm run build

      - name: Run e2e tests
        env:
          HOME: /root
        run: npm run test:e2e

      - name: Upload test reports
        if: failure()
        uses: actions/upload-artifact@v6
        with:
          name: playwright-artifacts
          path: frontend/playwright-report

  lint-backend:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Set up the repository
        uses: actions/checkout@v5

      - name: Set up JDK ${{ vars.JAVA_VERSION }}
        uses: actions/setup-java@v5
        with:
          distribution: ${{ vars.JAVA_DIST }}
          java-version: ${{ vars.JAVA_VERSION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: ${{ vars.GRADLE_VERSION }}

      - name: Lint
        run: gradle checkstyleMain

      - name: Upload lint reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v6
        with:
          name: lint-report
          path: backend/build/reports/checkstyle
          retention-days: 7

  test-backend:
    runs-on: self-hosted
    needs:
    - lint-backend
    defaults:
      run:
        working-directory: backend

    services:
      postgres:
        image: cytomine/postgis:${{ vars.POSTGIS_VERSION }}
        env:
          POSTGRES_NAME: appstore
          POSTGRES_USER: appstore
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Set up the repository
        uses: actions/checkout@v5

      - name: Set up JDK ${{ vars.JAVA_VERSION }}
        uses: actions/setup-java@v5
        with:
          distribution: ${{ vars.JAVA_DIST }}
          java-version: ${{ vars.JAVA_VERSION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: ${{ vars.GRADLE_VERSION }}

      - name: Test backend
        run: gradle :test --no-daemon
        env:
          DB_NAME: appstore
          DB_USERNAME: appstore
          DB_PASSWORD: password

      - name: Upload test reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v6
        with:
          name: reports
          path: backend/build/reports/
          retention-days: 7

      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v6
        with:
          name: test-results
          path: backend/build/test-results/
          retention-days: 7

      - name: Upload Java Code Coverage (JaCoCo)
        if: ${{ always() }}
        uses: actions/upload-artifact@v6
        with:
          name: jacoco
          path: backend/build/jacoco/
          retention-days: 7

  docker-images:
    needs: [e2e-tests-frontend]
    uses: ./.github/workflows/docker.yaml
    secrets: inherit

  helm-tests:
    needs: [docker-images]
    uses: ./.github/workflows/helm-test.yaml
    secrets: inherit
